environment:
  nodejs_version: "18"

branches:
  only:
    - master
    - main

cache:
  - node_modules
  - '%LOCALAPPDATA%\\Yarn'

install:
  - yarn install

build: off

build_script:
  - yarn build

test_script:
  - yarn lint  